# Generated by Django 5.0.6 on 2024-05-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Ex: example@example.com', max_length=255, unique=True, verbose_name='Email Address')),
                ('second_name', models.TextField(max_length=32, verbose_name='Second name')),
                ('first_name', models.TextField(max_length=32, verbose_name='First name')),
                ('surname', models.TextField(blank=True, max_length=32, null=True, verbose_name='Surname')),
                ('position', models.TextField(max_length=100, verbose_name='Position')),
                ('department', models.TextField(max_length=100, verbose_name='Department')),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
