# Generated by Django 5.0.6 on 2024-05-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='invitee',
        ),
        migrations.AddField(
            model_name='invite',
            name='invitee_email',
            field=models.EmailField(default='a@a.ru', help_text='Ex: example@example.com', max_length=255, verbose_name='Email Address'),
            preserve_default=False,
        ),
    ]
