# Generated by Django 5.0.6 on 2024-05-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_is_superuser'),
        ('account', '0004_remove_invite_invitee_invite_invitee_email'),
    ]

    operations = [
    ]
