# Generated by Django 5.0.6 on 2024-05-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], default='low', max_length=16),
        ),
    ]
