# Generated by Django 5.0.6 on 2024-05-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20240519_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], default='low'),
        ),
    ]
