# Generated by Django 5.0.6 on 2024-05-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_chatmessage_user_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(0, 'Тип не определен'), (1, 'Личное'), (2, 'Встреча'), (3, 'Тренинг'), (4, 'Конференция')], default='none'),
        ),
    ]
