# Generated by Django 5.0.6 on 2024-05-22 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(default='event:calendar', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifs', to='event.event'),
        ),
    ]
